services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.rails7.2
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  bundle:
  mysql_data:
